on: [push]

name: AzureARMDeploy

permissions:
  id-token: write
  contents: read

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check out the CARML repo
      run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/Azure/ResourceModules.git
          ls
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep
    - name: Run Bicep Param linter
      run: az bicep build-params --file ./parameters.bicepparam

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v3
      - name: Check out the CARML repo
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/Azure/ResourceModules.git
          ls
      - uses: azure/arm-deploy@v1
        name: Run preflight validation
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          parameters: ./parameters.bicepparam
          deploymentMode: Validate
  preview:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v3
      - name: Check out the CARML repo
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/Azure/ResourceModules.git
          ls
      - uses: azure/arm-deploy@v1
        name: Run what-if
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          parameters: ./parameters.bicepparam
          failOnStdErr: false
          additionalArguments: --what-if
  deploy:
    runs-on: ubuntu-latest
    environment: testEnvironment
    needs: preview
    steps:
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v3
      - name: Check out the CARML repo
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/Azure/ResourceModules.git
          ls
      - uses: azure/arm-deploy@v1
        name: Deploy Bicep file
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          parameters: ./parameters.bicepparam
          failOnStdErr: false
          